module.exports = {
  GetOpenid:"Action=GetOpenid",//获取用户openid
  UpdateUser:"Action=UpdateUser", //更新用户信息
  GetUserDetail:"Action=GetUserDetail",//获取用户基本信息
  GetPhone:"Action=GetPhone",//获取用户手机号码
  GetSysInfo:"Action=GetSysInfo", //获取系统基础数据
  GetMajor:"Action=GetMajor", //获取专业分类
  GetBanner:"Action=GetBanner", //获取轮播图
  GetIndexNav:"Action=GetIndexNav", //获取首页导航
  GetIndexSubject:"Action=GetIndexSubject", // 获取首页真题
  GetBranchCourse:"Action=GetBranchCourse",//获取首页免费试听课程
  GetIndexAdv:"Action=GetIndexAdv", //获取首页广告位
  GetActivityRedClickNum:"Action=ActivityRedClickNum", //首页最新活动增加点击量
  GetHotRed:"Action=GetHotRed", //获取首页热点资讯
  GetIndexCourse:"Action=GetIndexCourse", //获取首页精品课程
  GetQuestion:"Action=GetQuestion", //获取问题列表
  GetGratisCourse:"Action=GetGratisCourse", //获取免费课程列表
  GetGratisDetail:"Action=GetGratisDetail", //获取免费课程详情
  GetYsTask:"Action=GetYsTask", //获取佑森作业列表
  GetYsTaskDetail:"Action=YsTaskDetail", //获取佑森作业详情
  CollectInfo:"Action=CollectInfo", //收藏真题/章节/作业
  GetUserCourse:"Action=GetUserCourse", //获取我的课程
  UserQuestion:"Action=UserQuestion", //我的提问列表
  SubmitQuestion:"Action=SubmitQuestion",//用户提问
  GetActivityRed:"Action=GetActivityRed", //获取最新活动列表
  GetActivityDetail:"Action=ActivityDetail", //获取活动详情
  GetExperience:"Action=GetExperience", //获取活动心得
  GetIndustryNews:"Action=GetIndustryNews",//获取首页行业动态
  GetNewsDetail:"Action=NewsDetail", //获取行业动态详情
  GetBoutiqueCourse:"Action=BoutiqueCourse",//获取精品课程列表
  GetBoutiqueDetail:"Action=BoutiqueDetail",//获取精品课程详情
  GetElseBanner:"Action=GetElseBanner",//获取其他banner图
  GetBrotherMajor:"Action=GetBrotherMajor", // 获取同类的三级专业分类
  GetSubjectTopic:"Action=GetSubjectTopic", //获取章节练习列表
  GetSubject:"Action=GetSubject", //获取真题列表
  SubmitBoutiqueOrder:"Action=SubmitBoutiqueOrder", //提交精品课程订单
  PayBtqOrder:"Action=PayBtqOrder", //发起精品课程支付
  GetSubjectQuestion:"Action=SubjectQuestion", //获取真题所有题目（和章节练习共用）
  UserAnswer:"Action=UserAnswer", //用户答题接口（和章节练习共用）
  SubmitSubject:"Action=SubmitSubject", //真题练习交卷接口（和章节练习共用）
  SetRecordAnswerTime:"Action=RecordAnswerTime", //记录即时答题最新时间（和章节练习共用）
  GetCollectList:"Action=GetCollectList", //获取我的收藏列表
  GetCollectTopic:"Action=GetCollectTopic", //获取收藏列表(章节)
  GetBtqOrder:"Action=GetBtqOrder", //获取课程订单列表
  GetBtqOrderDetail:"Action=GetBtqOrderDetail",//获取精品课程订单详情
  CancelBtqOrder:"Action=CancelBtqOrder", //取消订单
  GetActivityConfig:"Action=ActivityConfig", //获取活动中心设置信息
  GetGroupList:"Action=GetGroup", //获取拼团列表数据
  GetGroupDetail:"Action=GroupDetail", // 获取拼团详情
  PayGroup:"Action=PayGroup",//支付发起拼团
  GetGroupRed:"Action=GetGroupRed", //获取拼团底部推荐
  GetMeans:"Action=GetMeans",//领取拼团资料
  ResetGroup:"Action=ResetGroup",//重新开始拼团
  GetGroupImmediate:"Action=GroupImmediate", //实时获取拼团人数和状态
  SubmitGroupOrder:"Action=SubmitGroupOrder",//拼团提交课程订单（原价购买）
  GetGroupOrder:"Action=GetGroupOrder", //获取拼团订单
  GetGuideList:"Action=GuideList", // 获取报考指南信息列表
  GetGuideDetail:"Action=GuideDetail", //通过信息ID获取报考指南详情
  GetProcessDetail:"Action=ProcessDetail", //通过坐标获取报考指南详情
  GetSubjectError:"Action=GetSubjectError", //获取错题集列表
  GetTestSubjectError:"Action=TestSubjectError", //获取错题集详情
  UserErrorAnswer:"Action=ErrorAnswer",// 错题集答题接口
  GetTestSubjectCollect:"Action=TestSubjectCollect",//获取收藏
  UserCollectAnswer:"Action=CollectAnswer",//收藏答题
  GetUserMeans:"Action=UserMeans",//获取个人资料列表
  GetMeansDoc:"Action=MeansDoc",//获取资料子类文档
  GetRandomCount:"Action=GetRandomCount", //获取当天随机答题的人数
  ClearSubject:"Action=ClearSubject", //清空已交卷的真题记录和数据
  GetExperienceDetail:"Action=ExperienceDetail",//获取通关心得详情
  GetErrorTopic:"Action=GetErrorTopic", // 获取错题列表(章节)
  GetStartAnswer:"Action=StartAnswer", //获取真题信息详情
  GetTNextQuestion:"Action=NextQuestion", //获取下一道题目
  GetPrevQuestion:"Action=PrevQuestion", //获取上一题
  GetLastAnswer:"Action=LastAnswer", //获取答题最后一页数据
  GetAnswerCard:"Action=AnswerCard", //获取真题答题卡详细数据
  GetQuestionDetail:"Action=QuestionDetail", //从答题卡其中一道题进入详情
  GetEstimateSubject:"Action=GetEstimateSubject", // 获取真题估分列表
  GetEstimateAppoint:"Action=EstimateAppoint", //提交估分预约记录
  SetEstimateClear:"Action=EstimateClear", //真题估分清零
  UserEstimate:"Action=UserEstimate", //估分答题接口
  SubmitEstimate:"Action=SubmitEstimate", //真题估分提交接口
  EstimateResult:"Action=EstimateResult", //获取真题估分结果
  GetQrCode:"Action=GetQrCode", //获取个人分享小程序码
  GetChildSubject:"Action=GetChildSubject", //根据章节ID获取真题练习
  Getmajorzm:"getmajorzm", //根据科目ID获取免费课程
  Getmajordetailedzm:"getmajordetailedzm", //根据免费课程ID获取详细内容
}