// AUTOGENERATED — DO NOT EDIT.
//
// Source: deeptutor/services/bi_metrics.py BI_METRICS
// Regenerate: python -m scripts.gen_bi_metrics_ts
// Drift check: pytest tests/services/test_bi_metrics.py -k test_metric_registry_ts_in_sync
//
// Round 3 D fix (single source of truth). The previous hand-written
// bi-v2-metric-registry.ts has been deleted; all frontend code now imports
// from this generated file. Adding a new metric: edit BI_METRICS in
// bi_metrics.py, then re-run the codegen.

export type BiTrustLevel = "A" | "B" | "C" | "D";

export type BiV2MetricDef = {
  metric_id: string;
  label_aliases: string[];
  group: string;
  definition: string;
  authority: string;
  trust: BiTrustLevel;
  owner: string;
  drilldown_hash: string;
  refresh_cadence: string;
  degraded_note: string;
};

export const BI_V2_METRICS: BiV2MetricDef[] = [
  {
    metric_id: "effective_learning_members",
    label_aliases: ["有效学习成功会员数", "有效学习成功会员"],
    group: "north_star",
    definition: "窗口内有真实手机号会员身份，并完成至少一次有效学习会话或学习成果的会员数。",
    authority: "bi_service",
    trust: "B",
    owner: "boss",
    drilldown_hash: "member-ops",
    refresh_cadence: "近实时 (overview API)",
    degraded_note: "session store / member_console 任一降级时数值偏低；overview banner 同步标红。",
  },
  {
    metric_id: "registered_members",
    label_aliases: ["真实注册会员数", "真实注册会员"],
    group: "growth",
    definition: "通过会员系统 canonical member 口径过滤后的真实手机号会员数，不包含测试、探针和演练账号。",
    authority: "member_console",
    trust: "A",
    owner: "ops",
    drilldown_hash: "member-ops",
    refresh_cadence: "近实时 (Supabase REST)",
    degraded_note: "",
  },
  {
    metric_id: "activated_members",
    label_aliases: ["激活会员数", "活跃学习者"],
    group: "growth",
    definition: "窗口内至少有一次真实学习会话的注册会员数。",
    authority: "bi_service",
    trust: "B",
    owner: "product",
    drilldown_hash: "member-ops",
    refresh_cadence: "近实时 (聚合 session_store)",
    degraded_note: "session_store 同步延迟时窗口尾部样本偏少。",
  },
  {
    metric_id: "active_learning_sessions",
    label_aliases: ["活跃学习会话", "活跃学习会话数"],
    group: "overview",
    definition: "窗口内更新过的会话数。",
    authority: "bi_service",
    trust: "B",
    owner: "product",
    drilldown_hash: "member-ops",
    refresh_cadence: "近实时",
    degraded_note: "TutorBot 回写降级时仅基于客户端 events，可能漏会话。",
  },
  {
    metric_id: "success_turn_rate",
    label_aliases: ["回合成功率"],
    group: "ai_quality",
    definition: "成功完成的回合数占总回合数的比例。",
    authority: "bi_service",
    trust: "B",
    owner: "quality",
    drilldown_hash: "feedback",
    refresh_cadence: "近实时",
    degraded_note: "Langfuse 评估延迟时分子滞后，分母先到，比例偏低。",
  },
  {
    metric_id: "avg_session_depth",
    label_aliases: ["平均会话深度"],
    group: "overview",
    definition: "每个会话的平均消息数。",
    authority: "bi_service",
    trust: "B",
    owner: "product",
    drilldown_hash: "overview",
    refresh_cadence: "近实时",
    degraded_note: "",
  },
  {
    metric_id: "notebook_saves",
    label_aliases: ["Notebook 保存", "笔记沉淀"],
    group: "learning_evidence",
    definition: "问题笔记沉淀量。",
    authority: "bi_service",
    trust: "B",
    owner: "product",
    drilldown_hash: "overview",
    refresh_cadence: "近实时",
    degraded_note: "",
  },
  {
    metric_id: "total_cost_usd",
    label_aliases: ["总成本", "近 24h LLM 成本", "近 7d 总成本"],
    group: "unit_economics",
    definition: "窗口内全量 AI 调用总成本 (USD)，measured（provider 回报）与 estimated（tiktoken 估算）分列。",
    authority: "observability.usage_ledger",
    trust: "B",
    owner: "platform",
    drilldown_hash: "ops",
    refresh_cadence: "近实时 (UsageLedger 聚合)",
    degraded_note: "estimated 分量按定价表估算；与 Langfuse/官方账单残差由对账 harness 持续核对。",
  },
  {
    metric_id: "total_tokens",
    label_aliases: ["总 Token"],
    group: "unit_economics",
    definition: "窗口内全量 AI 调用总 token 数（measured + estimated 分列）。",
    authority: "observability.usage_ledger",
    trust: "B",
    owner: "platform",
    drilldown_hash: "ops",
    refresh_cadence: "近实时 (UsageLedger 聚合)",
    degraded_note: "",
  },
  {
    metric_id: "today_cost_usd",
    label_aliases: ["今日成本"],
    group: "unit_economics",
    definition: "自然日（本地时区）内全量 AI 调用总成本 (USD)。",
    authority: "observability.usage_ledger",
    trust: "B",
    owner: "boss",
    drilldown_hash: "ops",
    refresh_cadence: "近实时 (UsageLedger 聚合)",
    degraded_note: "",
  },
  {
    metric_id: "avg_turn_cost_usd",
    label_aliases: ["平均回合成本"],
    group: "unit_economics",
    definition: "窗口总成本除以窗口回合数；回合数来自会话事实，成本来自 UsageLedger。",
    authority: "observability.usage_ledger",
    trust: "B",
    owner: "platform",
    drilldown_hash: "ops",
    refresh_cadence: "近实时",
    degraded_note: "分子含窗口内非回合内调用（评分/合成等），高于纯聊天回合边际成本。",
  },
  {
    metric_id: "member_active_count",
    label_aliases: ["活跃会员"],
    group: "member_ops",
    definition: "member_console canonical 口径下当前状态为 active 的会员数。",
    authority: "member_console",
    trust: "A",
    owner: "ops",
    drilldown_hash: "member-ops",
    refresh_cadence: "近实时 (Supabase REST)",
    degraded_note: "",
  },
  {
    metric_id: "expiring_soon_members",
    label_aliases: ["7 天内到期", "即将到期会员"],
    group: "member_ops",
    definition: "7 天内会员权益到期的 canonical 会员数。",
    authority: "member_console",
    trust: "A",
    owner: "ops",
    drilldown_hash: "member-ops",
    refresh_cadence: "近实时 (Supabase REST)",
    degraded_note: "",
  },
  {
    metric_id: "renewal_risk_members",
    label_aliases: ["续费风险会员数", "续费风险会员", "流失预警"],
    group: "member_ops",
    definition: "即将到期、沉默、高风险或高成本低效果的会员集合。",
    authority: "member_console",
    trust: "B",
    owner: "ops",
    drilldown_hash: "member-ops",
    refresh_cadence: "每 5 分钟 (member_console 聚合)",
    degraded_note: "学习证据未同步时风险评分偏低。",
  },
  {
    metric_id: "member_health_score",
    label_aliases: ["会员健康评分", "会员健康"],
    group: "member_health",
    definition: "由学习行为、会员价值、学习效果、AI 体验和运营关系组成的透明风险评分；样本不足时只展示风险标签和原因。",
    authority: "bi_service",
    trust: "C",
    owner: "ops",
    drilldown_hash: "member-ops",
    refresh_cadence: "每 15 分钟",
    degraded_note: "样本量 < 阈值时仅展示风险标签和原因，不展示分值。",
  },
  {
    metric_id: "mastery_improvement",
    label_aliases: ["章节掌握度提升"],
    group: "teaching_effect",
    definition: "基于 member learner state 中章节掌握度和弱点闭环信号计算的学习效果指标。",
    authority: "learner_state",
    trust: "C",
    owner: "teaching",
    drilldown_hash: "teaching-effect",
    refresh_cadence: "每 15 分钟",
    degraded_note: "learner_state read model 同步延迟时窗口尾部掌握度偏低；样本量 < 10 时不展示。",
  },
  {
    metric_id: "ai_quality_score",
    label_aliases: ["AI 教学质量分", "AI 质量"],
    group: "ai_quality",
    definition: "v1 承载工程成功率（成功回合占比）作为代理；反馈/追问/RAG 信号综合分列入 P3。",
    authority: "bi_service",
    trust: "B",
    owner: "quality",
    drilldown_hash: "feedback",
    refresh_cadence: "近实时",
    degraded_note: "Langfuse / 用户反馈源任一缺数据时切到 placeholder，不参与排名。",
  },
  {
    metric_id: "cost_per_effective_learning",
    label_aliases: ["单有效学习成本", "单次学习成本"],
    group: "unit_economics",
    definition: "窗口总 AI 成本除以有效学习成功会员数；收入未接入时只展示成本侧。",
    authority: "bi_service",
    trust: "B",
    owner: "boss",
    drilldown_hash: "ops",
    refresh_cadence: "每 5 分钟",
    degraded_note: "成本估算 C 级时此指标也降级到 C 级。",
  },
  {
    metric_id: "behavior.module.open_count",
    label_aliases: ["模块打开次数"],
    group: "product_behavior",
    definition: "窗口内用户进入学习产品模块的次数，来自 product_behavior_events indexed raw read model。",
    authority: "product_behavior_store",
    trust: "B",
    owner: "product",
    drilldown_hash: "member-ops",
    refresh_cadence: "近实时 indexed raw read",
    degraded_note: "visit_id、release_id 或 section visibility 缺失时降级为 B/C。",
  },
  {
    metric_id: "behavior.learning_report.section_view_count",
    label_aliases: ["学情 section 浏览次数"],
    group: "product_behavior",
    definition: "窗口内学情页 section 进入视口或 fallback 渲染曝光次数。",
    authority: "product_behavior_store",
    trust: "B",
    owner: "product",
    drilldown_hash: "member-ops",
    refresh_cadence: "近实时 indexed raw read",
    degraded_note: "小程序/yousen 曝光口径未完成三端一致 smoke 前保持 B 级。",
  },
  {
    metric_id: "behavior.funnel.report_to_training",
    label_aliases: ["学情到训练转化"],
    group: "product_behavior",
    definition: "学情浏览后进入训练的用户或 visit 占比。",
    authority: "product_behavior_store",
    trust: "B",
    owner: "product",
    drilldown_hash: "member-ops",
    refresh_cadence: "近实时 indexed raw read",
    degraded_note: "缺 visit_id 时不进入 A 级漏斗。",
  },
  {
    metric_id: "behavior.member_ops.report_high_no_action",
    label_aliases: ["学情高频无行动"],
    group: "product_behavior",
    definition: "7 天学情打开不少于 3 次且训练/复测开始为 0 的会员队列。",
    authority: "product_behavior_store",
    trust: "B",
    owner: "ops",
    drilldown_hash: "member-ops",
    refresh_cadence: "近实时 indexed raw read",
    degraded_note: "低可信 cohort 只允许人工参考，不进入自动运营队列。",
  },
  {
    metric_id: "data_trust_score",
    label_aliases: ["数据可信度分", "数据可信"],
    group: "data_trust",
    definition: "基于接口降级、数据源缺口、指标口径完整度和更新时间形成的可信度摘要。",
    authority: "bi_service",
    trust: "A",
    owner: "engineering",
    drilldown_hash: "ops",
    refresh_cadence: "近实时",
    degraded_note: "v1 不计算数值分（payload value 显式为 null），仅暴露 status 与 degraded_modules；数值化列入 P3。",
  },
];

const LABEL_TO_METRIC = new Map<string, BiV2MetricDef>();
for (const m of BI_V2_METRICS) {
  for (const alias of m.label_aliases) {
    LABEL_TO_METRIC.set(alias.trim(), m);
  }
}

const FALLBACK: BiV2MetricDef = {
  metric_id: "unknown",
  label_aliases: [],
  group: "unknown",
  definition: "未注册的指标。建议添加到 deeptutor/services/bi_metrics.py BI_METRICS。",
  authority: "unknown",
  trust: "D",
  owner: "unowned",
  drilldown_hash: "overview",
  refresh_cadence: "unknown",
  degraded_note: "指标未注册，元数据不可信。",
};

export function findMetricByLabel(label: string | undefined): BiV2MetricDef {
  if (!label) return FALLBACK;
  const trimmed = label.trim();
  return LABEL_TO_METRIC.get(trimmed) ?? FALLBACK;
}

export function findMetricById(metricId: string | undefined): BiV2MetricDef {
  if (!metricId) return FALLBACK;
  const trimmed = metricId.trim();
  return BI_V2_METRICS.find((m) => m.metric_id === trimmed) ?? FALLBACK;
}
