// AUTOGENERATED — DO NOT EDIT.
//
// Source: deeptutor/contracts/bi_v2_write_endpoints.py WRITE_ENDPOINTS
// Regenerate: python -m scripts.gen_bi_write_endpoints_ts
// Drift guard: pytest tests/api/test_bi_write_endpoints_registry.py
//
// Round 4 S2 enforced invariant: every BI v2 audited write must reference an
// entry in this registry. useAuditedAction collapses the endpoint argument to
// the union keyof typeof WRITE_ENDPOINTS so unregistered URLs fail to compile.


export type BiV2WriteEndpoint = {
  readonly key: string;
  readonly method: "POST" | "PATCH" | "DELETE";
  readonly path_template: string;
  readonly requires_idempotency: boolean;
  readonly description: string;
  readonly audit_action: string;
};

export const WRITE_ENDPOINTS = {
  ["member.conversation.view_full"]: {
    key: "member.conversation.view_full",
    method: "POST",
    path_template: "/api/v1/member/{user_id}/conversations/{session_id}/view-audit",
    requires_idempotency: true,
    description: "Privacy audit: admin requests full chat replay for a member. Body must include reason (≥ 4 chars or one of the 5 whitelisted reason codes). Backend appends to audit_log + dedupes by (action, X-Idempotency-Key).",
    audit_action: "conversation_view",
  },
  ["feedback.ai.triage"]: {
    key: "feedback.ai.triage",
    method: "POST",
    path_template: "/api/v1/bi/feedback/{feedback_id}/triage",
    requires_idempotency: true,
    description: "AI feedback triage: admin marks a feedback item open, triaged, or ignored. Backend updates ai_feedback metadata and appends feedback_triage to member_console audit_log with idempotency dedup.",
    audit_action: "feedback_triage",
  },
  ["feedback.invite_test.update"]: {
    key: "feedback.invite_test.update",
    method: "PATCH",
    path_template: "/api/v1/bi/invite-test/applications/{application_id}",
    requires_idempotency: true,
    description: "Invite-test application edit: growth ops updates applicant status, contact/profile corrections, callback preference, and operator note. Backend updates invite_test_applications and records invite_test_application_update audit with idempotency dedup.",
    audit_action: "invite_test_application_update",
  },
  ["feedback.invite_test.delete"]: {
    key: "feedback.invite_test.delete",
    method: "DELETE",
    path_template: "/api/v1/bi/invite-test/applications/{application_id}",
    requires_idempotency: true,
    description: "Invite-test application delete: growth ops soft-deletes an application by archiving it. Backend hides archived applications from the default pool and records invite_test_application_delete audit with idempotency dedup.",
    audit_action: "invite_test_application_delete",
  },
  ["feedback.luban_feedback.update"]: {
    key: "feedback.luban_feedback.update",
    method: "PATCH",
    path_template: "/api/v1/bi/luban-feedback/responses/{response_id}",
    requires_idempotency: true,
    description: "Luban survey follow-up edit: growth ops updates only the operator-owned status and operator_note fields. Backend preserves the original survey answers and records luban_feedback_response_update audit with idempotency dedup.",
    audit_action: "luban_feedback_response_update",
  },
  ["member.ops_action.record"]: {
    key: "member.ops_action.record",
    method: "POST",
    path_template: "/api/v1/bi/member/{user_id}/ops-action",
    requires_idempotency: true,
    description: "Member low-risk ops action: mark contacted, add an ops note, or join follow-up queue. Backend writes an ops_action note and ops_action_result audit with idempotency dedup.",
    audit_action: "ops_action_result",
  },
  ["bi.export.request"]: {
    key: "bi.export.request",
    method: "POST",
    path_template: "/api/v1/bi/export-jobs",
    requires_idempotency: true,
    description: "BI export request: admin asks for a scrubbed export job. Backend records bi_export_request audit with dataset, filters, scrubbing, rate-limit metadata, and idempotency dedup before any export job is shown in the UI. product_behavior_raw is the only P0 raw_mode=true dataset; all other datasets remain scrubbed. P0 records the raw export job and audit trail; actual raw CSV extraction is deferred until the export worker supports behavior rows.",
    audit_action: "bi_export_request",
  },
} as const satisfies Record<string, BiV2WriteEndpoint>;

export type BiV2WriteEndpointKey = "member.conversation.view_full" | "feedback.ai.triage" | "feedback.invite_test.update" | "feedback.invite_test.delete" | "feedback.luban_feedback.update" | "member.ops_action.record" | "bi.export.request";

export const ALL_BI_V2_WRITE_KEYS: BiV2WriteEndpointKey[] = [
  "member.conversation.view_full",
  "feedback.ai.triage",
  "feedback.invite_test.update",
  "feedback.invite_test.delete",
  "feedback.luban_feedback.update",
  "member.ops_action.record",
  "bi.export.request",
];

// Static export retained so older imports continue compiling. Prefer
// the typed WRITE_ENDPOINTS map above for new code.
export const WRITE_ENDPOINT_LIST: readonly BiV2WriteEndpoint[] = [
  {
    key: "member.conversation.view_full",
    method: "POST",
    path_template: "/api/v1/member/{user_id}/conversations/{session_id}/view-audit",
    requires_idempotency: true,
    description: "Privacy audit: admin requests full chat replay for a member. Body must include reason (≥ 4 chars or one of the 5 whitelisted reason codes). Backend appends to audit_log + dedupes by (action, X-Idempotency-Key).",
    audit_action: "conversation_view",
  },
  {
    key: "feedback.ai.triage",
    method: "POST",
    path_template: "/api/v1/bi/feedback/{feedback_id}/triage",
    requires_idempotency: true,
    description: "AI feedback triage: admin marks a feedback item open, triaged, or ignored. Backend updates ai_feedback metadata and appends feedback_triage to member_console audit_log with idempotency dedup.",
    audit_action: "feedback_triage",
  },
  {
    key: "feedback.invite_test.update",
    method: "PATCH",
    path_template: "/api/v1/bi/invite-test/applications/{application_id}",
    requires_idempotency: true,
    description: "Invite-test application edit: growth ops updates applicant status, contact/profile corrections, callback preference, and operator note. Backend updates invite_test_applications and records invite_test_application_update audit with idempotency dedup.",
    audit_action: "invite_test_application_update",
  },
  {
    key: "feedback.invite_test.delete",
    method: "DELETE",
    path_template: "/api/v1/bi/invite-test/applications/{application_id}",
    requires_idempotency: true,
    description: "Invite-test application delete: growth ops soft-deletes an application by archiving it. Backend hides archived applications from the default pool and records invite_test_application_delete audit with idempotency dedup.",
    audit_action: "invite_test_application_delete",
  },
  {
    key: "feedback.luban_feedback.update",
    method: "PATCH",
    path_template: "/api/v1/bi/luban-feedback/responses/{response_id}",
    requires_idempotency: true,
    description: "Luban survey follow-up edit: growth ops updates only the operator-owned status and operator_note fields. Backend preserves the original survey answers and records luban_feedback_response_update audit with idempotency dedup.",
    audit_action: "luban_feedback_response_update",
  },
  {
    key: "member.ops_action.record",
    method: "POST",
    path_template: "/api/v1/bi/member/{user_id}/ops-action",
    requires_idempotency: true,
    description: "Member low-risk ops action: mark contacted, add an ops note, or join follow-up queue. Backend writes an ops_action note and ops_action_result audit with idempotency dedup.",
    audit_action: "ops_action_result",
  },
  {
    key: "bi.export.request",
    method: "POST",
    path_template: "/api/v1/bi/export-jobs",
    requires_idempotency: true,
    description: "BI export request: admin asks for a scrubbed export job. Backend records bi_export_request audit with dataset, filters, scrubbing, rate-limit metadata, and idempotency dedup before any export job is shown in the UI. product_behavior_raw is the only P0 raw_mode=true dataset; all other datasets remain scrubbed. P0 records the raw export job and audit trail; actual raw CSV extraction is deferred until the export worker supports behavior rows.",
    audit_action: "bi_export_request",
  },
];

export function resolveWritePath(
  key: BiV2WriteEndpointKey,
  params: Record<string, string | number>,
): {
  method: BiV2WriteEndpoint["method"];
  path: string;
  requiresIdempotency: boolean;
  auditAction: string;
} {
  const endpoint = WRITE_ENDPOINTS[key];
  let path: string = endpoint.path_template;
  for (const [name, value] of Object.entries(params)) {
    path = path.split(`{${name}}`).join(encodeURIComponent(String(value)));
  }
  if (path.includes("{")) {
    throw new Error(`resolveWritePath: missing params for ${endpoint.path_template} (got ${JSON.stringify(params)})`);
  }
  return {
    method: endpoint.method,
    path,
    requiresIdempotency: endpoint.requires_idempotency,
    auditAction: endpoint.audit_action,
  };
}
