// AUTOGENERATED — DO NOT EDIT.
//
// Source: deeptutor/contracts/bi_v2_write_endpoints.py WRITE_ENDPOINTS
// Regenerate: python -m scripts.gen_bi_write_endpoints_ts
// Drift guard: pytest tests/api/test_bi_write_endpoints_registry.py
//
// Round 4 S2 enforced invariant: every BI v2 audited write must reference an
// entry in this registry. useAuditedAction collapses the endpoint argument to
// the union keyof typeof WRITE_ENDPOINTS so unregistered URLs fail to compile.


export type BiV2WriteEndpoint = {
  readonly key: string;
  readonly method: "POST" | "PATCH" | "DELETE";
  readonly path_template: string;
  readonly requires_idempotency: boolean;
  readonly description: string;
  readonly audit_action: string;
};

export const WRITE_ENDPOINTS = {
  ["member.conversation.view_full"]: {
    key: "member.conversation.view_full",
    method: "POST",
    path_template: "/api/v1/member/{user_id}/conversations/{session_id}/view-audit",
    requires_idempotency: true,
    description: "Privacy audit: admin requests full chat replay for a member. Body must include reason (≥ 4 chars or one of the 5 whitelisted reason codes). Backend appends to audit_log + dedupes by (action, X-Idempotency-Key).",
    audit_action: "conversation_view",
  },
} as const satisfies Record<string, BiV2WriteEndpoint>;

export type BiV2WriteEndpointKey = "member.conversation.view_full";

export const ALL_BI_V2_WRITE_KEYS: BiV2WriteEndpointKey[] = [
  "member.conversation.view_full",
];

// Static export retained so older imports continue compiling. Prefer
// the typed WRITE_ENDPOINTS map above for new code.
export const WRITE_ENDPOINT_LIST: readonly BiV2WriteEndpoint[] = [
  {
    key: "member.conversation.view_full",
    method: "POST",
    path_template: "/api/v1/member/{user_id}/conversations/{session_id}/view-audit",
    requires_idempotency: true,
    description: "Privacy audit: admin requests full chat replay for a member. Body must include reason (≥ 4 chars or one of the 5 whitelisted reason codes). Backend appends to audit_log + dedupes by (action, X-Idempotency-Key).",
    audit_action: "conversation_view",
  },
];

export function resolveWritePath(
  key: BiV2WriteEndpointKey,
  params: Record<string, string | number>,
): {
  method: BiV2WriteEndpoint["method"];
  path: string;
  requiresIdempotency: boolean;
  auditAction: string;
} {
  const endpoint = WRITE_ENDPOINTS[key];
  let path: string = endpoint.path_template;
  for (const [name, value] of Object.entries(params)) {
    path = path.split(`{${name}}`).join(encodeURIComponent(String(value)));
  }
  if (path.includes("{")) {
    throw new Error(`resolveWritePath: missing params for ${endpoint.path_template} (got ${JSON.stringify(params)})`);
  }
  return {
    method: endpoint.method,
    path,
    requiresIdempotency: endpoint.requires_idempotency,
    auditAction: endpoint.audit_action,
  };
}
