var APP_BRAND_NAME = "鲁班智考";
var LOGIN_KICKER = APP_BRAND_NAME;
var BI_WORKBENCH_TITLE = APP_BRAND_NAME + " BI 工作台";

module.exports = {
  APP_BRAND_NAME: APP_BRAND_NAME,
  LOGIN_KICKER: LOGIN_KICKER,
  BI_WORKBENCH_TITLE: BI_WORKBENCH_TITLE,
};
