"""Generate web/lib/bi-v2-write-endpoints.generated.ts from WRITE_ENDPOINTS.

Round 4 S2. Backend ``deeptutor/contracts/bi_v2_write_endpoints.py`` is the
single source of truth for every audited BI v2 write path. This script mirrors
that registry into a typed TypeScript module so:

  * ``useAuditedAction`` collapses its ``endpoint.url`` parameter into
    ``keyof typeof WRITE_ENDPOINTS``; callers asking for an unregistered key
    fail at compile time.
  * The pytest drift guard
    ``tests/api/test_bi_write_endpoints_registry.py::test_write_endpoints_ts_in_sync``
    fails CI if the generated file ever diverges from the registry.

Usage:
    python -m scripts.gen_bi_write_endpoints_ts            # writes the .ts file
    python -m scripts.gen_bi_write_endpoints_ts --check    # exit 1 if drift
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from deeptutor.contracts.bi_v2_write_endpoints import WRITE_ENDPOINTS, WriteEndpoint


REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "web" / "lib" / "bi-v2-write-endpoints.generated.ts"

HEADER = """// AUTOGENERATED — DO NOT EDIT.
//
// Source: deeptutor/contracts/bi_v2_write_endpoints.py WRITE_ENDPOINTS
// Regenerate: python -m scripts.gen_bi_write_endpoints_ts
// Drift guard: pytest tests/api/test_bi_write_endpoints_registry.py
//
// Round 4 S2 enforced invariant: every BI v2 audited write must reference an
// entry in this registry. useAuditedAction collapses the endpoint argument to
// the union keyof typeof WRITE_ENDPOINTS so unregistered URLs fail to compile.
"""


def _ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_endpoint(endpoint: WriteEndpoint) -> str:
    fields = [
        f"    key: {_ts_string(endpoint.key)}",
        f"    method: {_ts_string(endpoint.method)}",
        f"    path_template: {_ts_string(endpoint.path_template)}",
        f"    requires_idempotency: {'true' if endpoint.requires_idempotency else 'false'}",
        f"    description: {_ts_string(endpoint.description)}",
        f"    audit_action: {_ts_string(endpoint.audit_action)}",
    ]
    return "  {\n" + ",\n".join(fields) + ",\n  }"


def render_module() -> str:
    nl = "\n"
    endpoints_body = (",\n").join(render_endpoint(e) for e in WRITE_ENDPOINTS)
    keys_union = " | ".join(_ts_string(e.key) for e in WRITE_ENDPOINTS)
    map_entries = (",\n").join(
        f"  [{_ts_string(e.key)}]: {render_endpoint(e).lstrip()}" for e in WRITE_ENDPOINTS
    )
    key_list = (",\n").join(f"  {_ts_string(e.key)}" for e in WRITE_ENDPOINTS)

    parts = [
        HEADER,
        "",
        "export type BiV2WriteEndpoint = {",
        "  readonly key: string;",
        '  readonly method: "POST" | "PATCH" | "DELETE";',
        "  readonly path_template: string;",
        "  readonly requires_idempotency: boolean;",
        "  readonly description: string;",
        "  readonly audit_action: string;",
        "};",
        "",
        "export const WRITE_ENDPOINTS = {",
        map_entries + ",",
        "} as const satisfies Record<string, BiV2WriteEndpoint>;",
        "",
        f"export type BiV2WriteEndpointKey = {keys_union};",
        "",
        "export const ALL_BI_V2_WRITE_KEYS: BiV2WriteEndpointKey[] = [",
        key_list + ",",
        "];",
        "",
        "// Static export retained so older imports continue compiling. Prefer",
        "// the typed WRITE_ENDPOINTS map above for new code.",
        "export const WRITE_ENDPOINT_LIST: readonly BiV2WriteEndpoint[] = [",
        endpoints_body + ",",
        "];",
        "",
        "export function resolveWritePath(",
        "  key: BiV2WriteEndpointKey,",
        "  params: Record<string, string | number>,",
        "): {",
        '  method: BiV2WriteEndpoint["method"];',
        "  path: string;",
        "  requiresIdempotency: boolean;",
        "  auditAction: string;",
        "} {",
        "  const endpoint = WRITE_ENDPOINTS[key];",
        "  let path: string = endpoint.path_template;",
        "  for (const [name, value] of Object.entries(params)) {",
        "    path = path.split(`{${name}}`).join(encodeURIComponent(String(value)));",
        "  }",
        '  if (path.includes("{")) {',
        '    throw new Error(`resolveWritePath: missing params for ${endpoint.path_template} (got ${JSON.stringify(params)})`);',
        "  }",
        "  return {",
        "    method: endpoint.method,",
        "    path,",
        "    requiresIdempotency: endpoint.requires_idempotency,",
        "    auditAction: endpoint.audit_action,",
        "  };",
        "}",
        "",
    ]
    return nl.join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit 1 on drift.")
    args = parser.parse_args()

    expected = render_module()
    if args.check:
        actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if actual != expected:
            sys.stderr.write(
                "bi-v2-write-endpoints.generated.ts is out of sync with WRITE_ENDPOINTS.\n"
                "Run: python -m scripts.gen_bi_write_endpoints_ts\n"
            )
            return 1
        return 0

    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    sys.stdout.write(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
