"""Generate web/lib/bi-v2-metric-registry.generated.ts from BI_METRICS.

Round 3 D single-source-of-truth fix. Replaces the hand-maintained
``web/lib/bi-v2-metric-registry.ts`` (annotated "Kept in sync manually") with
a generated mirror so backend ``deeptutor/services/bi_metrics.py`` is the
canonical authority. ``tests/services/test_bi_metrics.py::
test_metric_registry_ts_in_sync`` guards drift in CI.

Usage:
    python -m scripts.gen_bi_metrics_ts            # writes the .ts file
    python -m scripts.gen_bi_metrics_ts --check    # exit 1 if drift detected

The generated file is the only TS module consumed by the frontend; the legacy
hand-written file is deleted as part of Round 3 D.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable

from deeptutor.services.bi_metrics import BI_METRICS, BIMetricDefinition


REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "web" / "lib" / "bi-v2-metric-registry.generated.ts"

HEADER = """// AUTOGENERATED — DO NOT EDIT.
//
// Source: deeptutor/services/bi_metrics.py BI_METRICS
// Regenerate: python -m scripts.gen_bi_metrics_ts
// Drift check: pytest tests/services/test_bi_metrics.py -k test_metric_registry_ts_in_sync
//
// Round 3 D fix (single source of truth). The previous hand-written
// bi-v2-metric-registry.ts has been deleted; all frontend code now imports
// from this generated file. Adding a new metric: edit BI_METRICS in
// bi_metrics.py, then re-run the codegen.
"""


def _ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _ts_string_array(values: Iterable[str]) -> str:
    items = ", ".join(_ts_string(v) for v in values)
    return f"[{items}]"


def render_metric(metric: BIMetricDefinition) -> str:
    aliases = (metric.label, *metric.label_aliases)
    fields = [
        f"    metric_id: {_ts_string(metric.metric_id)}",
        f"    label_aliases: {_ts_string_array(aliases)}",
        f"    group: {_ts_string(metric.group)}",
        f"    definition: {_ts_string(metric.definition)}",
        f"    authority: {_ts_string(metric.authority)}",
        f"    trust: {_ts_string(metric.trust_level)}",
        f"    owner: {_ts_string(metric.owner)}",
        f"    drilldown_hash: {_ts_string(metric.drilldown.replace('_', '-'))}",
        f"    refresh_cadence: {_ts_string(metric.refresh_cadence)}",
        f"    degraded_note: {_ts_string(metric.degraded_note)}",
    ]
    body = ",\n".join(fields)
    return "  {\n" + body + ",\n  }"


def render_module() -> str:
    metric_blocks = ",\n".join(render_metric(m) for m in BI_METRICS)
    return f"""{HEADER}
export type BiTrustLevel = "A" | "B" | "C" | "D";

export type BiV2MetricDef = {{
  metric_id: string;
  label_aliases: string[];
  group: string;
  definition: string;
  authority: string;
  trust: BiTrustLevel;
  owner: string;
  drilldown_hash: string;
  refresh_cadence: string;
  degraded_note: string;
}};

export const BI_V2_METRICS: BiV2MetricDef[] = [
{metric_blocks},
];

const LABEL_TO_METRIC = new Map<string, BiV2MetricDef>();
for (const m of BI_V2_METRICS) {{
  for (const alias of m.label_aliases) {{
    LABEL_TO_METRIC.set(alias.trim(), m);
  }}
}}

const FALLBACK: BiV2MetricDef = {{
  metric_id: "unknown",
  label_aliases: [],
  group: "unknown",
  definition: "未注册的指标。建议添加到 deeptutor/services/bi_metrics.py BI_METRICS。",
  authority: "unknown",
  trust: "D",
  owner: "unowned",
  drilldown_hash: "overview",
  refresh_cadence: "unknown",
  degraded_note: "指标未注册，元数据不可信。",
}};

export function findMetricByLabel(label: string | undefined): BiV2MetricDef {{
  if (!label) return FALLBACK;
  const trimmed = label.trim();
  return LABEL_TO_METRIC.get(trimmed) ?? FALLBACK;
}}

export function findMetricById(metricId: string | undefined): BiV2MetricDef {{
  if (!metricId) return FALLBACK;
  const trimmed = metricId.trim();
  return BI_V2_METRICS.find((m) => m.metric_id === trimmed) ?? FALLBACK;
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the generated file differs from BI_METRICS.",
    )
    args = parser.parse_args()

    expected = render_module()
    if args.check:
        actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if actual != expected:
            sys.stderr.write(
                f"bi-v2-metric-registry.generated.ts is out of sync with BI_METRICS.\n"
                f"Re-run: python -m scripts.gen_bi_metrics_ts\n"
            )
            return 1
        return 0

    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    sys.stdout.write(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
